(()=>{
  const ready=()=>{
    document.body.classList.add('master-v3');
    document.title='反詐實驗室 FRAUD LAB｜AI 防詐查證工具';
    const theme=document.querySelector('meta[name="theme-color"]');
    if(theme)theme.setAttribute('content','#03101f');
    const wrap=document.querySelector('.wrap');
    if(!wrap||document.querySelector('.mv3-shell'))return;
    const mast=wrap.querySelector('.masthead');if(mast)mast.style.display='none';
    const tabs=wrap.querySelector('.tabs');if(tabs)tabs.id='legacy-tools';
    wrap.classList.add('mv3-tools-panel');
    const shell=document.createElement('div');
    shell.className='mv3-shell';
    shell.innerHTML=`
<header class="mv3-nav"><a class="mv3-brand" href="#mv3-home" aria-label="回首頁"><i class="mv3-logo"></i><div><b>反詐實驗室</b><small>FRAUD LAB</small></div></a><nav class="mv3-links"><a href="#mv3-home">首頁</a><a href="#mv3-check">詐騙檢測</a><a href="#mv3-verify">查證流程</a><a href="#mv3-news">防詐提醒</a><a href="#mv3-about">關於我們</a><a class="mv3-165" href="tel:165">165 求助專線</a></nav><button class="mv3-share-top" id="mv3ShareTop">分享給朋友</button></header>
<section id="mv3-home" class="mv3-hero"><div class="mv3-copy"><div class="mv3-kicker">ANTI-FRAUD INTELLIGENCE</div><h1>AI 守護你<br><span>遠離詐騙陷阱</span></h1><p class="mv3-lead">一個讓不懂 AI 的人，也能直接使用的防詐工具。</p><div class="mv3-points"><span><i>⚡</i><b>快速檢測</b><small>立即分析風險</small></span><span><i>◎</i><b>專業資料庫</b><small>持續更新詐騙手法</small></span><span><i>♥</i><b>守護家人</b><small>長輩也能輕鬆使用</small></span></div><div class="mv3-note">少一個人受騙，就是多一個家庭的安心。<em>— 三寶爸</em></div></div><div class="mv3-visual" aria-hidden="true"><div class="mv3-bot"><div class="mv3-face"><i></i><i></i><b></b></div><span class="mv3-antenna"></span></div><div class="mv3-shield"><div class="mv3-lock"><i></i></div></div><div class="mv3-float mv3-f1">可疑簡訊</div><div class="mv3-float mv3-f2">假投資群組</div><div class="mv3-float mv3-f3">假客服</div><div class="mv3-float mv3-f4">釣魚網址</div><div class="mv3-handwrite">詐騙不會消失<br>但我們可以更聰明！</div></div></section>
<section id="mv3-check" class="mv3-checkbox"><div class="mv3-checktabs"><button class="on" data-quick="text">▣ 文字檢測</button><button data-quick="image">▧ 圖片截圖檢測</button><button data-quick="url">🔗 網址檢查</button><span>不用安裝 App・打開就能用</span></div><div class="mv3-checkbody"><textarea id="mv3QuickInput" placeholder="請貼上可疑的文字、簡訊內容、對話內容或網址…\n例如：投資、借錢、物流通知、客服訊息、中獎通知"></textarea><div class="mv3-checkactions"><button id="mv3Paste">貼上範例</button><button id="mv3Clear">清空內容</button><button class="primary" id="mv3QuickGo">⌕ 開始檢測<small>AI 即時分析風險</small></button></div><div class="mv3-samples"><b>試試這些常見案例：</b><button>假物流簡訊</button><button>假投資邀約</button><button>假客服通知</button><button>網購詐騙</button><button>交友詐騙</button><button>中獎通知</button><button>假公務機關</button></div></div></section>
<section id="mv3-verify" class="mv3-verify"><div class="mv3-sectionhead"><small>WHY FRAUD LAB</small><h2>我們不只是 AI 回答，而是完整的防詐查證</h2><p>把 AI 理解力、規則引擎、網址驗證、資料庫比對與行動建議整合成同一個流程。</p></div><div class="mv3-verifygrid"><article><i>01</i><b>智能辨識</b><p>理解整段訊息與對話脈絡，不只抓單一關鍵字。</p></article><article><i>02</i><b>規則檢查</b><p>比對常見詐騙話術、付款要求、OTP 與高風險行為。</p></article><article><i>03</i><b>網址驗證</b><p>拆出真正網域，檢查品牌名稱與網址是否一致。</p></article><article><i>04</i><b>資料庫比對</b><p>持續補充最新案例、已知風險特徵與實際誤判案例。</p></article><article><i>05</i><b>給出建議</b><p>不只告訴你風險，還會告訴你下一步該怎麼做。</p></article></div><div class="mv3-trustbar"><span>◉ 不用安裝 App</span><span>◉ 一般人也能直接使用</span><span>◉ 核心規則持續更新</span><span>◉ 高風險時建議直接聯絡 165</span></div></section>
<section id="mv3-tools" class="mv3-toolgrid"><div class="mv3-sectionhead"><small>SMART SECURITY TOOLS</small><h2>四個入口，一眼就知道怎麼用</h2></div><article class="mv3-toolcard blue" data-tab="0"><div class="mv3-toolicon">文</div><div><h3>文字快篩</h3><p>貼上可疑訊息，快速抓出危險話術與行為模式。</p></div><b>立即前往 ›</b></article><article class="mv3-toolcard purple" data-tab="0" data-deep="1"><div class="mv3-toolicon">圖</div><div><h3>AI 截圖化驗</h3><p>上傳對話截圖，讓 AI 讀完整上下文再判斷。</p></div><b>立即前往 ›</b></article><article class="mv3-toolcard gold" data-tab="1"><div class="mv3-toolicon">測</div><div><h3>防詐力測驗</h3><p>用實際案例測試自己能不能識破詐騙陷阱。</p></div><b>立即前往 ›</b></article><article class="mv3-toolcard green" data-tab="2"><div class="mv3-toolicon">鑑</div><div><h3>詐騙圖鑑</h3><p>整理常見劇本、話術與破解方式，持續更新。</p></div><b>立即前往 ›</b></article></section>
<section id="mv3-news" class="mv3-lower"><article class="mv3-alert"><header>⚠ 近期高發詐騙</header><ol><li>假冒電信或物流通知</li><li>假投資群組與 AI 換臉</li><li>假購物平台一頁式廣告</li><li>假客服要求操作 ATM</li><li>交友後引導投資</li></ol></article><article class="mv3-tips"><header>💡 防詐小技巧</header><ul><li>不點陌生連結</li><li>不提供個資與驗證碼</li><li>不隨意下載 App</li><li>遇到可疑先查證</li><li>多與家人朋友討論</li></ul></article><article id="mv3-about" class="mv3-dad"><header>💬 三寶爸想說的話</header><p>我只是個普通的三寶爸，也曾經差一點被騙。</p><p>所以我把 AI 做成一個不懂 AI 的人也能直接使用的防詐工具，希望幫更多人少走一點冤枉路。</p><strong>詐騙不會消失，但我們可以一起更聰明。</strong></article></section>
<section class="mv3-emergency"><div><h3>如果你已經匯款、提供帳戶或驗證碼</h3><p>不要再和對方爭辯，先保留證據並聯絡警方或 165。</p></div><a href="tel:165">立即撥打 165</a></section>
<section id="mv3-support" class="mv3-support"><small>COMMUNITY SUPPORT</small><h3>一起把反詐工具做得更好</h3><p>如果你測到誤判、遇到新的詐騙話術，歡迎把案例提供給三寶爸。每一個案例都可能成為下一次更新的重要資料。</p><div class="mv3-support-actions"><button id="mv3Share">分享反詐網站</button><button id="mv3SupportOpen">了解如何支持</button></div><div class="mv3-support-detail" id="mv3SupportDetail" hidden><button class="mv3-support-close" id="mv3SupportClose">×</button><h4>支持反詐實驗室持續更新</h4><p>AI 鑑定、後台、案例整理與規則更新都需要持續維護。支持完全自由，不支持也不影響任何免費功能。</p><a href="https://lin.ee/YewRM1L" target="_blank" rel="noopener">透過 LINE 聯絡三寶爸</a></div></section>
<footer class="mv3-footer"><div><b>反詐實驗室 FRAUD LAB</b><p>用 AI 守護每一個需要的人</p></div><nav><a href="#mv3-home">首頁</a><a href="#mv3-check">詐騙檢測</a><a href="#mv3-verify">查證流程</a><a href="#mv3-news">防詐提醒</a><a href="tel:165">165</a></nav><small>© 2026 反詐實驗室｜三寶爸製作</small></footer>`;
    wrap.parentNode.insertBefore(shell,wrap);
    const back=document.createElement('button');back.className='mv3-back';back.type='button';back.textContent='← 回到反詐實驗室首頁';wrap.insertBefore(back,wrap.firstChild);
    const openTab=(n,deep)=>{document.body.classList.add('mv3-tools-open');const btn=tabs&&tabs.querySelectorAll('.tab')[n];if(btn)btn.click();if(deep)setTimeout(()=>document.querySelector('#mbAI')?.click(),100);setTimeout(()=>wrap.scrollIntoView({behavior:'smooth',block:'start'}),140)};
    back.addEventListener('click',()=>{document.body.classList.remove('mv3-tools-open');setTimeout(()=>document.querySelector('#mv3-home')?.scrollIntoView({behavior:'smooth'}),30)});
    shell.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openTab(+el.dataset.tab,!!el.dataset.deep)}));
    const q=shell.querySelector('#mv3QuickInput');const submit=()=>{const v=q.value.trim();if(!v){q.focus();return}openTab(0,false);setTimeout(()=>{const ta=document.querySelector('#qText');if(ta){ta.value=v;ta.dispatchEvent(new Event('input',{bubbles:true}))}document.querySelector('#qBtn')?.click()},220)};
    shell.querySelector('#mv3QuickGo')?.addEventListener('click',submit);q?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')submit()});
    shell.querySelector('#mv3Clear')?.addEventListener('click',()=>{q.value='';q.focus()});shell.querySelector('#mv3Paste')?.addEventListener('click',()=>{q.value='有人說要免費送我釣竿，只要付 58 元運費，並傳來一個陌生物流網址叫我付款。';q.focus()});
    const sampleMap={'假物流簡訊':'您的包裹配送異常，請立即點擊陌生網址補繳 58 元運費。','假投資邀約':'老師帶單保證獲利，加入群組下載指定投資 APP。','假客服通知':'客服表示訂單設定錯誤，要求操作 ATM 解除分期。','網購詐騙':'賣家要求脫離平台私下匯款，價格比市價便宜很多。','交友詐騙':'網友聊天一陣子後開始推薦虛擬貨幣投資平台。','中獎通知':'恭喜中獎，需先支付手續費才能領獎。','假公務機關':'自稱檢察官要求提供帳戶並配合資金監管。'};
    shell.querySelectorAll('.mv3-samples button').forEach(btn=>btn.addEventListener('click',()=>{q.value=sampleMap[btn.textContent]||'';q.focus()}));
    shell.querySelectorAll('[data-quick]').forEach(btn=>btn.addEventListener('click',()=>{shell.querySelectorAll('[data-quick]').forEach(b=>b.classList.remove('on'));btn.classList.add('on');if(btn.dataset.quick==='image')openTab(0,true);else q.focus()}));
    const share=async()=>{const data={title:'反詐實驗室 FRAUD LAB',text:'把可疑訊息、網址或截圖丟進來，先查再決定。',url:location.href.split('?')[0]};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);alert('網址已複製')}}catch{}};
    shell.querySelector('#mv3Share')?.addEventListener('click',share);shell.querySelector('#mv3ShareTop')?.addEventListener('click',share);
    const detail=shell.querySelector('#mv3SupportDetail');shell.querySelector('#mv3SupportOpen')?.addEventListener('click',()=>{detail.hidden=false;detail.scrollIntoView({behavior:'smooth',block:'center'})});shell.querySelector('#mv3SupportClose')?.addEventListener('click',()=>detail.hidden=true);
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();